# Required Skills Of An AI Engineer

Run `4-classify-job-postings.ipynb` first so that `Job Posting Data/2-llm_filtered_jobs.jsonl` exists.

This notebook uses an LLM to extract a normalized set of AI-engineering skills for each accepted job posting, saves the per-job results to `Job Posting Data/3-extracted_skills.jsonl`, and then calculates how often each skill appears across the postings.

In [7]:
import json
from pathlib import Path

import pandas as pd
from openai import OpenAI
from IPython.display import display

llm_filtered_jsonl_path = Path("Job Posting Data") / "2-llm_filtered_jobs.jsonl"
skills_jsonl_path = Path("Job Posting Data") / "3-extracted_skills.jsonl"

if not llm_filtered_jsonl_path.exists():
    raise FileNotFoundError(
        f"LLM-filtered jobs JSONL file not found: {llm_filtered_jsonl_path.resolve()}. Run 4-classify-job-postings.ipynb first."
    )

jobs = pd.read_json(llm_filtered_jsonl_path, lines=True)

if jobs.empty:
    raise ValueError("The LLM-filtered jobs JSONL file is empty. Run 4-classify-job-postings.ipynb first.")

if "description" not in jobs.columns:
    raise KeyError("The LLM-filtered jobs JSONL file must contain a 'description' column.")

jobs = jobs[jobs["description"].notna()].copy()
jobs["description"] = jobs["description"].astype(str).str.strip()
jobs = jobs[jobs["description"] != ""].copy()
jobs = jobs.reset_index(drop=True)

if jobs.empty:
    raise ValueError("The LLM-filtered jobs JSONL file contains no usable job descriptions for skill extraction.")

skill_categories = [
    "ai-engineering",
    "ml",
    "frontend",
    "backend",
    "databases",
    "data",
    "cloud",
    "ops",
    "languages",
    "other",
]

client = OpenAI()
max_description_chars = 6000
max_skills_per_job = 15
skill_results = []

instructions = """
You extract required skills from AI engineering job postings.

Extract the concrete required skills from each job posting.
Use the provided categories, but do not limit yourself to any predefined skill list.
Include a skill only when it is clearly required, strongly implied, or a central part of the role.
Do not include a skill just because the posting vaguely mentions AI.
Use concise normalized skill names like 'python', 'rag', 'prompt engineering', 'aws', 'docker', 'kubernetes', 'sql', 'langchain'.
Do not use category names themselves as skills unless the posting truly names that exact thing as a skill.
Return only the skills that are actually relevant for the posting.
Return at most 15 skills.
""".strip()

skill_schema = {
    "type": "object",
    "properties": {
        "skills": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "skill": {"type": "string", "minLength": 1, "maxLength": 60},
                    "category": {"type": "string", "enum": skill_categories}
                },
                "required": ["skill", "category"],
                "additionalProperties": False
            },
            "maxItems": 15
        }
    },
    "required": ["skills"],
    "additionalProperties": False,
}

category_text = "\n".join(f"- {category}" for category in skill_categories)

for i, (_, job) in enumerate(jobs.iterrows(), start=1):
    title = "" if pd.isna(job.get("title")) else str(job.get("title")).strip()
    company = "" if pd.isna(job.get("company")) else str(job.get("company")).strip()
    job_url = "" if pd.isna(job.get("job_url")) else str(job.get("job_url")).strip()
    description = str(job.get("description", "")).strip()

    description_for_prompt = description[:max_description_chars]
    if len(description) > max_description_chars:
        description_for_prompt += "\n\n[Description truncated for skill extraction.]"

    print(f"Extracting skills for job {i}/{len(jobs)}: {title} @ {company}")

    prompt = f"""Extract the required skills for this job posting.\n\nUse only these categories:\n{category_text}\n\nReturn concrete skills and assign each skill to one category. Return at most {max_skills_per_job} skills.\n\nTitle: {title}\nCompany: {company}\nURL: {job_url}\n\nDescription:\n{description_for_prompt}"""

    result = None
    last_error = None

    for max_output_tokens in (400, 800, 1200):
        response = client.responses.create(
            model="gpt-5.4-mini",
            instructions=instructions,
            input=prompt,
            max_output_tokens=max_output_tokens,
            text={
                "format": {
                    "type": "json_schema",
                    "name": "ai_engineering_skill_extraction",
                    "schema": skill_schema,
                    "strict": True,
                },
                "verbosity": "low",
            },
        )

        try:
            result = json.loads(response.output_text)
            break
        except json.JSONDecodeError as exc:
            last_error = exc
            if response.incomplete_details is None and response.status == "completed":
                continue

    if result is None:
        raise ValueError(
            f"Failed to parse structured skill output for '{title}' at '{company}'. Last error: {last_error}"
        )
    extracted_skills = []
    seen_pairs = set()

    for item in result.get("skills", []):
        raw_skill = str(item.get("skill", "")).strip()
        category = str(item.get("category", "")).strip().lower()

        if not raw_skill or category not in skill_categories:
            continue

        normalized_skill = raw_skill.lower()
        pair = (normalized_skill, category)
        if pair in seen_pairs:
            continue

        seen_pairs.add(pair)
        extracted_skills.append(
            {
                "skill": normalized_skill,
                "category": category,
            }
        )

    extracted_skills = sorted(extracted_skills, key=lambda item: (item["category"], item["skill"]))
    extracted_skill_labels = [f"{item['skill']} [{item['category']}]" for item in extracted_skills]

    skill_results.append(
        {
            "title": title,
            "company": company,
            "job_url": job_url,
            "extracted_skills": extracted_skills,
            "extracted_skill_labels": extracted_skill_labels,
        }
    )

skills_by_job = pd.DataFrame(skill_results)
skills_by_job.to_json(skills_jsonl_path, orient='records', lines=True, force_ascii=False)

print(f"Saved extracted skills to: {skills_jsonl_path.resolve()}")
skills_by_job_to_show = skills_by_job[["title", "company", "extracted_skill_labels"]].copy()
skills_by_job_to_show.index = range(1, len(skills_by_job_to_show) + 1)
display(skills_by_job_to_show)

Extracting skills for job 1/40: Principal AI Engineer @ VideoAmp
Extracting skills for job 2/40: AI Engineer / Agentic and Generative AI @ Realign
Extracting skills for job 3/40: AI Engineer, Enterprise AI (Principal/Sr. Principal/Distinguished) @ Palo Alto Networks
Extracting skills for job 4/40: Junior Applied AI Engineer- HRIS @ Fortinet
Extracting skills for job 5/40: Principal AI Engineer @ Burrell Behavioral Health
Extracting skills for job 6/40: Principal, Software Engineer - GenAi @ Walmart
Extracting skills for job 7/40: Gen AI Engineer @ Persistent Systems
Extracting skills for job 8/40: Senior Gen AI Engineer (USC/GC) W2 Role @ Hudson Manpower
Extracting skills for job 9/40: Senior Artificial Intelligence (AI) Engineer (SWE-3) @ Leidos
Extracting skills for job 10/40: Senior AI/ML Engineer @ Quest Global
Extracting skills for job 11/40: Principal Engineer - Agentic AI (US) @ TD
Extracting skills for job 12/40: CrowdStrike AI Security Engineer @ Openkyber
Extracting skills for job 13/40: Generative AI Engineer @ BigSpring (evolved into Reps)
Extracting skills for job 14/40: AI Engineer @ SoFi
Extracting skills for job 15/40: Python AI Engineer @ Arka Innovate
Extracting skills for job 16/40: Senior AI Engineer @ H2O.ai
Extracting skills for job 17/40: AI (artificial intelligence) Engineer @ Royalty Pharma
Extracting skills for job 18/40: AI Engineer @ scalr
Extracting skills for job 19/40: AI Engineer @ Provenir
Extracting skills for job 20/40: Sr. AI Engineer @ Rula
Extracting skills for job 21/40: Principal AI Engineer, Ads AI @ LinkedIn
Extracting skills for job 22/40: AI Engineer @ Deliberately Incorporated
Extracting skills for job 23/40: Distinguished AI Engineer- Talent Marketplace @ LinkedIn
Extracting skills for job 24/40: Principal Staff AI Engineer, Ads AI @ LinkedIn
Extracting skills for job 25/40: Sr. AI Engineer @ Greylock Partners
Extracting skills for job 26/40: Applied AI Engineer - AI Solutions @ Snorkel AI
Extracting skills for job 27/40: Senior Staff AI Engineer - Enterprise AI (Agentic AI) @ LinkedIn
Extracting skills for job 28/40: AI Engineer @ Delta-v Capital
Extracting skills for job 29/40: AI Engineer @ Aspen One
Extracting skills for job 30/40: AI Engineer - Python @ CoreAi Consulting
Extracting skills for job 31/40: AI Software Engineer @ NVIDIA
Extracting skills for job 32/40: Agentic AI Engineer @ Eigen Labs
Extracting skills for job 33/40: Applied AI Engineer (AI Adoption) @ Jump Trading
Extracting skills for job 34/40: Founding AI Engineer @ Hyperspell (YC F25)
Extracting skills for job 35/40: Senior AI Engineer (AI Engineering) @ Lendable
Extracting skills for job 36/40: AI Engineer @ PepsiCo
Extracting skills for job 37/40: Senior AI Engineer @ HCA Healthcare
Extracting skills for job 38/40: Senior AI Engineer @ Elios Talent
Extracting skills for job 39/40: Applied AI Engineer @ neuroGrid
Extracting skills for job 40/40: Principal Enterprise AI Engineer @ ZeroFox
Saved extracted skills to: /Users/lukaslechner/PythonProjects/ai-engineering-foundations-labs/1-introduction/Job Posting Data/3-extracted_skills.jsonl

,title,company,extracted_skill_labels
1,Principal AI Engineer,VideoAmp,"[agentic workflows [ai-engineering], evaluatio..."
2,AI Engineer / Agentic and Generative AI,Realign,"[agentic ai [ai-engineering], evaluation frame..."
3,"AI Engineer, Enterprise AI (Principal/Sr. Prin...",Palo Alto Networks,"[agentic ai [ai-engineering], ai observability..."
4,Junior Applied AI Engineer- HRIS,Fortinet,"[chatbots [ai-engineering], llms [ai-engineeri..."
5,Principal AI Engineer,Burrell Behavioral Health,"[context management [ai-engineering], groundin..."
6,"Principal, Software Engineer - GenAi",Walmart,"[agents [ai-engineering], genai [ai-engineerin..."
7,Gen AI Engineer,Persistent Systems,"[genai architecture [ai-engineering], langchai..."
8,Senior Gen AI Engineer (USC/GC) W2 Role,Hudson Manpower,"[crewai [ai-engineering], generative ai [ai-en..."
9,Senior Artificial Intelligence (AI) Engineer (...,Leidos,"[hugging face [ai-engineering], openai api [ai..."
10,Senior AI/ML Engineer,Quest Global,"[agentic ai [ai-engineering], genai [ai-engine..."
11,Principal Engineer - Agentic AI (US),TD,"[agentic workflows [ai-engineering], autogen [..."
12,CrowdStrike AI Security Engineer,Openkyber,"[prompt engineering [ai-engineering], django [..."
13,Generative AI Engineer,BigSpring (evolved into Reps),"[agentic workflows [ai-engineering], langchain..."
14,AI Engineer,SoFi,"[agentic ai systems [ai-engineering], ai obser..."
15,Python AI Engineer,Arka Innovate,"[agentic ai [ai-engineering], langgraph [ai-en..."
16,Senior AI Engineer,H2O.ai,"[agentic ai [ai-engineering], guardrails [ai-e..."
17,AI (artificial intelligence) Engineer,Royalty Pharma,"[agentic ai [ai-engineering], ai workflows [ai..."
18,AI Engineer,scalr,"[agentic ai [ai-engineering], llms [ai-enginee..."
19,AI Engineer,Provenir,"[langchain [ai-engineering], llm deployment [a..."
20,Sr. AI Engineer,Rula,"[agents [ai-engineering], evaluation pipelines..."
21,"Principal AI Engineer, Ads AI",LinkedIn,"[agentic systems [ai-engineering], ai engineer..."
22,AI Engineer,Deliberately Incorporated,"[langchain [ai-engineering], llm deployment [a..."
23,Distinguished AI Engineer- Talent Marketplace,LinkedIn,"[agentic ai systems [ai-engineering], ai syste..."
24,"Principal Staff AI Engineer, Ads AI",LinkedIn,"[agentic systems [ai-engineering], ai engineer..."
25,Sr. AI Engineer,Greylock Partners,"[agentic applications [ai-engineering], llm sy..."
26,Applied AI Engineer - AI Solutions,Snorkel AI,"[rag [ai-engineering], fastapi [backend], mypy..."
27,Senior Staff AI Engineer - Enterprise AI (Agen...,LinkedIn,"[agentic architecture [ai-engineering], embedd..."
28,AI Engineer,Delta-v Capital,"[langchain [ai-engineering], large language mo..."
29,AI Engineer,Aspen One,"[ai agents [ai-engineering], anthropic claude ..."
30,AI Engineer - Python,CoreAi Consulting,"[embeddings [ai-engineering], langchain [ai-en..."
31,AI Software Engineer,NVIDIA,"[embeddings [ai-engineering], large language m..."
32,Agentic AI Engineer,Eigen Labs,"[agent orchestration [ai-engineering], agent r..."
33,Applied AI Engineer (AI Adoption),Jump Trading,"[agent design [ai-engineering], agent framewor..."
34,Founding AI Engineer,Hyperspell (YC F25),"[agentic architectures [ai-engineering], embed..."
35,Senior AI Engineer (AI Engineering),Lendable,"[llms [ai-engineering], mcp [ai-engineering], ..."
36,AI Engineer,PepsiCo,"[a2a [ai-engineering], agentic ai [ai-engineer..."
37,Senior AI Engineer,HCA Healthcare,"[agentic ai [ai-engineering], ai agents [ai-en..."
38,Senior AI Engineer,Elios Talent,"[ai workflow design [ai-engineering], llms [ai..."
39,Applied AI Engineer,neuroGrid,"[ai-powered workflows [ai-engineering], llms [..."
40,Principal Enterprise AI Engineer,ZeroFox,"[agentic systems [ai-engineering], ai governan..."

In [8]:
skills_by_job = pd.read_json(skills_jsonl_path, lines=True)

if skills_by_job.empty:
    raise ValueError("No extracted skills were found. Run the previous cell first.")

total_jobs = len(skills_by_job)
exploded = skills_by_job.explode("extracted_skills").copy()
exploded = exploded[exploded["extracted_skills"].notna()].copy()

if exploded.empty:
    raise ValueError("The extracted skills file does not contain any skills. Run the previous cell again.")

exploded["skill"] = exploded["extracted_skills"].apply(lambda item: item["skill"])
exploded["category"] = exploded["extracted_skills"].apply(lambda item: item["category"])
category_counts = []
skill_counts = []

for category in skill_categories:
    count = int(skills_by_job["extracted_skills"].apply(lambda skills: any(item["category"] == category for item in skills)).sum())
    percentage = round((count / total_jobs) * 100, 1)
    category_counts.append(
        {
            "category": category,
            "jobs_mentioning_category": count,
            "total_jobs": total_jobs,
            "percentage": percentage,
        }
    )

for (category, skill_name), skill_frame in exploded.groupby(["category", "skill"]):
    count = int(skill_frame.index.nunique())
    percentage = round((count / total_jobs) * 100, 1)
    skill_counts.append(
        {
            "category": category,
            "skill": skill_name,
            "jobs_mentioning_skill": count,
            "total_jobs": total_jobs,
            "percentage": percentage,
        }
    )

category_stats = pd.DataFrame(category_counts).sort_values(
    by=["jobs_mentioning_category", "category"], ascending=[False, True]
).reset_index(drop=True)

skill_stats = pd.DataFrame(skill_counts).sort_values(
    by=["jobs_mentioning_skill", "category", "skill"], ascending=[False, True, True]
).reset_index(drop=True)

category_stats["share_of_jobs"] = category_stats.apply(
    lambda row: f"{row['jobs_mentioning_category']}/{row['total_jobs']} ({row['percentage']}%)",
    axis=1,
)

skill_stats["share_of_jobs"] = skill_stats.apply(
    lambda row: f"{row['jobs_mentioning_skill']}/{row['total_jobs']} ({row['percentage']}%)",
    axis=1,
)

category_stats_to_show = category_stats[["category", "share_of_jobs"]].copy()
category_stats_to_show.index = range(1, len(category_stats_to_show) + 1)

top_25_skill_stats = skill_stats[["category", "skill", "share_of_jobs"]].head(25).copy()
top_25_skill_stats.index = range(1, len(top_25_skill_stats) + 1)

print(f"Top 25 skills out of {len(skill_stats)} extracted skills")
display(category_stats_to_show)
display(top_25_skill_stats)

for category in category_stats["category"]:
    category_top_10 = skill_stats[skill_stats["category"] == category][["skill", "share_of_jobs"]].head(10).copy()
    category_top_10.index = range(1, len(category_top_10) + 1)
    print(f"Top 10 skills for category: {category}")
    display(category_top_10)

Top 25 skills out of 305 extracted skills

          category   share_of_jobs
1   ai-engineering  40/40 (100.0%)
2        languages   33/40 (82.5%)
3          backend   30/40 (75.0%)
4              ops   25/40 (62.5%)
5            cloud   22/40 (55.0%)
6               ml   21/40 (52.5%)
7        databases   19/40 (47.5%)
8             data   16/40 (40.0%)
9            other   14/40 (35.0%)
10        frontend   10/40 (25.0%)

          category                  skill  share_of_jobs
1        languages                 python  32/40 (80.0%)
2   ai-engineering     prompt engineering  20/40 (50.0%)
3   ai-engineering                    rag  17/40 (42.5%)
4   ai-engineering              langchain  14/40 (35.0%)
5            cloud                    aws  12/40 (30.0%)
6   ai-engineering                   llms  11/40 (27.5%)
7   ai-engineering             agentic ai   9/40 (22.5%)
8              ops                 docker   9/40 (22.5%)
9        databases       vector databases   8/40 (20.0%)
10       languages             typescript   7/40 (17.5%)
11            data         data pipelines   6/40 (15.0%)
12       databases                    sql   6/40 (15.0%)
13        frontend                  react   6/40 (15.0%)
14              ml       machine learning   6/40 (15.0%)
15             ops                  ci/cd   6/40 (15.0%)
16  ai-engineering              langgraph   5/40 (12.5%)
17         backend             api design   5/40 (12.5%)
18         backend                fastapi   5/40 (12.5%)
19           cloud                  azure   5/40 (12.5%)
20           cloud                    gcp   5/40 (12.5%)
21  ai-engineering  evaluation frameworks   4/40 (10.0%)
22  ai-engineering  large language models   4/40 (10.0%)
23  ai-engineering                    mcp   4/40 (10.0%)
24         backend    distributed systems   4/40 (10.0%)
25           cloud           azure openai   4/40 (10.0%)

Top 10 skills for category: ai-engineering

                    skill  share_of_jobs
1      prompt engineering  20/40 (50.0%)
2                     rag  17/40 (42.5%)
3               langchain  14/40 (35.0%)
4                    llms  11/40 (27.5%)
5              agentic ai   9/40 (22.5%)
6               langgraph   5/40 (12.5%)
7   evaluation frameworks   4/40 (10.0%)
8   large language models   4/40 (10.0%)
9                     mcp   4/40 (10.0%)
10        agentic systems    3/40 (7.5%)

Top 10 skills for category: languages

                                               skill  share_of_jobs
1                                             python  32/40 (80.0%)
2                                         typescript   7/40 (17.5%)
3                                               java    3/40 (7.5%)
4                                         javascript    2/40 (5.0%)
5   backend language (javascript/typescript/java/go)    1/40 (2.5%)
6                                                  c    1/40 (2.5%)
7                                                 go    1/40 (2.5%)
8                                             golang    1/40 (2.5%)
9                                            node.js    1/40 (2.5%)
10                                            pytest    1/40 (2.5%)

Top 10 skills for category: backend

                   skill share_of_jobs
1             api design  5/40 (12.5%)
2                fastapi  5/40 (12.5%)
3    distributed systems  4/40 (10.0%)
4              rest apis   3/40 (7.5%)
5   software engineering   3/40 (7.5%)
6        api development   2/40 (5.0%)
7                   apis   2/40 (5.0%)
8                node.js   2/40 (5.0%)
9            ai/llm apis   1/40 (2.5%)
10       api integration   1/40 (2.5%)

Top 10 skills for category: ops

                      skill share_of_jobs
1                    docker  9/40 (22.5%)
2                     ci/cd  6/40 (15.0%)
3                kubernetes  4/40 (10.0%)
4                       git   2/40 (5.0%)
5             observability   2/40 (5.0%)
6   reliability engineering   2/40 (5.0%)
7         agile development   1/40 (2.5%)
8                   airflow   1/40 (2.5%)
9        cloudformation/cdk   1/40 (2.5%)
10         coding standards   1/40 (2.5%)

Top 10 skills for category: cloud

              skill  share_of_jobs
1               aws  12/40 (30.0%)
2             azure   5/40 (12.5%)
3               gcp   5/40 (12.5%)
4      azure openai   4/40 (10.0%)
5       aws bedrock    2/40 (5.0%)
6   cloud platforms    2/40 (5.0%)
7            lambda    2/40 (5.0%)
8           aws eks    1/40 (2.5%)
9     aws sagemaker    1/40 (2.5%)
10  azure ai search    1/40 (2.5%)

Top 10 skills for category: ml

                          skill share_of_jobs
1              machine learning  6/40 (15.0%)
2                           nlp  4/40 (10.0%)
3                       pytorch  4/40 (10.0%)
4              model evaluation   3/40 (7.5%)
5                    embeddings   2/40 (5.0%)
6                   fine-tuning   2/40 (5.0%)
7         large language models   2/40 (5.0%)
8                           llm   2/40 (5.0%)
9   natural language processing   2/40 (5.0%)
10       recommendation systems   2/40 (5.0%)

Top 10 skills for category: databases

                          skill share_of_jobs
1              vector databases  8/40 (20.0%)
2                           sql  6/40 (15.0%)
3                 data modeling   1/40 (2.5%)
4   data warehouse architecture   1/40 (2.5%)
5                 elasticsearch   1/40 (2.5%)
6                         faiss   1/40 (2.5%)
7                         nosql   1/40 (2.5%)
8                    postgresql   1/40 (2.5%)
9        semantic data modeling   1/40 (2.5%)
10                    snowflake   1/40 (2.5%)

Top 10 skills for category: data

                  skill share_of_jobs
1        data pipelines  6/40 (15.0%)
2      data engineering  4/40 (10.0%)
3             analytics   2/40 (5.0%)
4       data governance   2/40 (5.0%)
5           a/b testing   1/40 (2.5%)
6               airflow   1/40 (2.5%)
7              bi tools   1/40 (2.5%)
8              big data   1/40 (2.5%)
9   clinical trial data   1/40 (2.5%)
10        data chunking   1/40 (2.5%)

Top 10 skills for category: other

                             skill share_of_jobs
1             technical leadership   3/40 (7.5%)
2          technical communication   2/40 (5.0%)
3    advertising domain experience   1/40 (2.5%)
4                 computer science   1/40 (2.5%)
5                       consulting   1/40 (2.5%)
6   cross-functional collaboration   1/40 (2.5%)
7      customer-facing engineering   1/40 (2.5%)
8                        debugging   1/40 (2.5%)
9                 excel automation   1/40 (2.5%)
10              finance automation   1/40 (2.5%)

Top 10 skills for category: frontend

          skill share_of_jobs
1         react  6/40 (15.0%)
2  dashboarding   1/40 (2.5%)
3          htmx   1/40 (2.5%)
4       next.js   1/40 (2.5%)
5      react.js   1/40 (2.5%)
6    typescript   1/40 (2.5%)